### ISSUE TITLE
What is between it and the Docker difference

### ISSUE THREAD

**Issue by playgoods** [miguelgrinberg/slam#1]
thank you  Mr. Miguel 
i want ask . 
Is this an alternative to the construction worker

thank you

**Comment by miguelgrinberg** [comment]
@playgoods the AWS Lambda/API Gateway services provide a "serverless" set up, meaning that you do not need to set anything up. No need to run gunicorn, uWSGI, Docker containers, nginx or anything of that sort. You just deploy the code (with this tool, another tool or directly with AWS APIs), and AWS deploys your code and runs the server for you.

**Comment by playgoods** [comment]
thank you Mr. Miguel clear now :)
