### ISSUE TITLE
 flask module missing?

### ISSUE THREAD

**Issue by gberrido** [miguelgrinberg/slam#12]
Hello 
The tool seem quite powerful, I just have hard time getting the first run:
I run the slam advanced tutorial and seem to have the flask module missing, how can that be?
I run the files from the example and get:

slam logs --tail

Oct 01 21:42:39 START RequestId: af282c02-a6e0-11e7-a2f3-5b31c4c6f4b7 Version: $LATEST
Oct 01 21:42:39 (af271a63-a6e0-11e7-9075-cf62f417714a) Verifying Usage Plan for request: af271a63-a6e0-11e7-9075-cf62f417714a. API Key:  API Stage: wgbbbxjdr0/dev
Oct 01 21:42:39 (af271a63-a6e0-11e7-9075-cf62f417714a) API Key  authorized because method 'ANY /{proxy+}' does not require API Key. Request will not contribute to throttle or quota limits
Oct 01 21:42:39 (af271a63-a6e0-11e7-9075-cf62f417714a) Usage Plan check succeeded for API Key  and API Stage wgbbbxjdr0/dev
Oct 01 21:42:39 (af271a63-a6e0-11e7-9075-cf62f417714a) Starting execution for request: af271a63-a6e0-11e7-9075-cf62f417714a
Oct 01 21:42:39 (af271a63-a6e0-11e7-9075-cf62f417714a) HTTP Method: GET, Resource Path: /tasks
Oct 01 21:42:40 (af271a63-a6e0-11e7-9075-cf62f417714a) Execution failed due to configuration error: Malformed Lambda proxy response
Oct 01 21:42:40 (af271a63-a6e0-11e7-9075-cf62f417714a) Method completed with status: 502
Oct 01 21:42:40 No module named 'flask': ModuleNotFoundError
Traceback (most recent call last):
  File "/var/task/handler.py", line 39, in lambda_handler
    from tasks_api import app as app  # noqa
  File "/var/task/tasks_api.py", line 6, in <module>
    from flask import Flask, jsonify, abort, request, make_response, url_for
ModuleNotFoundError: No module named 'flask'
Oct 01 21:42:40 END RequestId: af282c02-a6e0-11e7-a2f3-5b31c4c6f4b7
Oct 01 21:42:40 REPORT RequestId: af282c02-a6e0-11e7-a2f3-5b31c4c6f4b7	Duration: 217.80 ms	Billed Duration: 300 ms 	Memory Size: 128 MB	Max Memory Used: 32 MB

What can be corrected?

Thanks for your help!

edit: currently using python 3.5.2 could that be too old?

**Comment by miguelgrinberg** [comment]
Can you please run a `slam build` and then inspect the zip file that is produced? There should be a `flask` directory in the top level.

**Comment by gberrido** [comment]
I don't seem to have it:
(venv) Macintosh:slamadv gberrido$ unzip lambda_package.20171001_202128.zip 
Archive:  lambda_package.20171001_202128.zip
replace handler.py? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: handler.py              
  inflating: requirements.txt        
  inflating: slam.yaml               
  inflating: slam_error.log          
  inflating: tasks_api.py            
  inflating: .slam/handler.py        
(venv) Macintosh:slamadv gberrido$ ls
handler.py				slam_error.log
lambda_package.20171001_202128.zip	tasks_api.py
requirements.txt			venv
slam.yaml
(venv) Macintosh:slamadv gberrido$

**Comment by miguelgrinberg** [comment]
It's not only Flask that is missing, you have no dependencies in the zip file at all. Are there any errors in the build log?

**Comment by gberrido** [comment]
I am not sure how to see the build log, there are no visible error messages when slam is building the package.

**Comment by miguelgrinberg** [comment]
The log is in the `slam_error.log` file.

**Comment by gberrido** [comment]
After a cleanup of all python 3 / tools and clean reinstall it all works fine.
Slam is really awesome, thanks again

**Comment by oldani** [comment]
Having the same issue here, i delete virtualenv and create it again but it does not work.

**Comment by fariqizwan** [comment]
Having the same problem too. The dependencies are not generated at all and no error in slam_error.log file. Using Python 2.7, do you know what could be the problem?
