### ISSUE TITLE
'async' (and 'invoke') are now Python keywords. 

### ISSUE THREAD

**Issue by FrithiofJensen** [miguelgrinberg/slam#16]
Running Slam on Python 3.8.1 fails with a Syntax Error because of a command line option and corresponding variable in main() called 'async', which is now a reserved Python keyword (from Python 3.7, I think). 

To test, I changed the 'async' option to 'nowait', since I lack imagination. 

This seems to work OK.

**Comment by miguelgrinberg** [comment]
Do you want to submit a PR with this change? `nowait` seems appropriate, I'm fine with that name.

**Comment by FrithiofJensen** [comment]
Sure, I can do that.
