### ISSUE TITLE
S3 Bucket naming conventions have changed

### ISSUE THREAD

**Issue by FrithiofJensen** [miguelgrinberg/slam#17]
The function '_ensure_bucket_exists(s3, bucket, region)' in 'cli.py' fails to create an S3 bucket and raises an exception:

> Unexpected error: An error occurred (InvalidBucketName) when calling the CreateBucket operation: The specified bucket is not valid. (ClientError)

I think this happens because one can no longer use capital letters in S3 bucket names, according to the most recent AWS-docs: https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

> Bucket names can consist only of lowercase letters, numbers, dots (.), and hyphens (-).

In the code (init(), line 119), it says:

`random.choice(string.ascii_uppercase + string.digits)`

Changing this line to:

`random.choice(string.ascii_lowercase + string.digits)`

makes the S3-bucket creation operation succeed.

**Comment by miguelgrinberg** [comment]
Would you submit a PR with this change?
