### ISSUE TITLE
Users Forum?

### ISSUE THREAD

**Issue by thielert** [miguelgrinberg/slam#5]
Miguel,
Is there a forum you would direct users to for discussing the implementation and development of “Slam”?
Thanks,
Tim

**Comment by miguelgrinberg** [comment]
The project is just a couple of weeks old, so no, at this time there are no forums other than this repository. Writing issues or questions here is fine by me.

**Comment by darrenjtaylor** [comment]
Is there anything in particular that differentiates this project from zappa or even chalice?  I just started using zappa, and as far as I can tell, this is very similar.

**Comment by miguelgrinberg** [comment]
@darrenjtaylor Zappa is a pretty good project, and is obviously much more advanced than slam, but it has one aspect that I don't like, which is that it deploys by invoking AWS APIs directly from its code. If you ever need to undo a Zappa deployment, you will have to figure out exactly what resources it created (the lambda, the API, any roles associated with them, its policies, it also touches DNS settings, and I really don't know if this is a complete list, only way to know is to look at the source code). If Zappa has bugs, or something changes in a future release, some piece of infrastructure may be left behind in your account when you delete a project. For these and similar reasons, I consider that this is the wrong way to run a cloud deployment.

Slam does not invoke random AWS APIs, and instead generates a single Cloudformation template that orchestrates the deployment. If you ever find the need to manually delete a Slam deployment, you have to delete just the Cloudformation template (which owns every single AWS resource created to support the deployment) and a S3 bucket that stores the Lambda code. That is it, you can clean a deployment up easily from the AWS Console in less than a minute. It is really impossible for any piece of infrastructure to ever be left behind.

**Comment by darrenjtaylor** [comment]
Right, I came to the same conclusion with respect to chalice.

As for zappa not cleaning up after itself after a `undeploy`, I guess I haven't played around with it enough to know that it doesn't completely clean things up.  I just ran a sample deployment and it looks like it kept the S3 bucket and the IAM role, but I don't see any remnants of APIGW or Lambda.  Not sure when you last tried it out, but I believe they are using Cloudformation to deploy / remove the stack.

**Comment by miguelgrinberg** [comment]
@darrenjtaylor I'm not say that Zappa leaks resources. As far as I know it doesn't. All I'm saying is that there is a possibility of that to happen. You are basically trusting the creation/destruction of your infrastructure to a piece of code that is maintained by someone else. Slam is also a piece of code maintained by someone else, but at least all it touches on your account is touched through cloudformation. There is a trace for every resource created, the cloudformation script is a sort of manifest.
